### ISSUE TITLE
Stem count is not cleared between subprocedure calls

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#471]
Assume the following rexx:

```
call subproc 10,"line"
call subproc 3,"record"
call subproc 5,"entry"
subproc: procedure
 arg count=.int,str=.string
 stem.1=''
 say "set "str", current hi="stem.0
 do i=1 to count
    stem.i=str' 'i
 end
 ## display stem
 do i=1 to count
    say stem.i
  end
return
```
While a stem variable is scoped locally within a subprocedure and its indexed elements (stem.i) are not accessible outside, the stem.0 count variable persists between calls. This can lead to misleading results if stem.0 is reused unintentionally.
To avoid this, explicitly clear stem.0 at the end of the procedure.
Result: 

```
138: Test timeout computed to be: 1500
138: set line, current hi=1
138: line 1
138: line 2
138: line 3
138: line 4
138: line 5
138: line 6
138: line 7
138: line 8
138: line 9
138: line 10
138: set record, current hi=10
138: record 1
138: record 2
138: record 3
138: set entry, current hi=10
138: entry 1
138: entry 2
138: entry 3
138: entry 4
138: entry 5
```

**Comment by adesutherland** [comment]
Thanks for the clear example!!

I have just pushed a fix - can you check?

**One thing I am worried about is the array_test has become very slow. Is this something to do with the fix making the test "fuller", or coincidence, or have I broken something?**

**Comment by adesutherland** [comment]
OK - Performance of arrays_test. If you add a line to set the array size upfront, like

options levelb
import arrays
import rxfnsb

imax=100000
array[imax+1]=''   /* Force Array Size - this makes it **MUCH** faster */

...

Massively faster, I will fix the array growth algorithm. What I am uncertain about is why the issue has only just appeared!!!

**Comment by Peter-Jacob** [comment]
Clearing stem count is solved. 
I ran it with several max counts, the problem occurs only for string arrays:
```
imax=10000
say time('l')
do i=1 to imax
   x.i="Record 123"
end
say time('l')
```
Result:
_134: 07:58:31.735195
134: 07:58:32.971660_

if I change it to imax=50000 it massively grows:
_134: 07:54:56.497049
134: 07:55:23.345476_ 

Following your suggestion:
```
imax=50000
x.imax='entry max'
say time('l')
do i=1 to imax
   x.i="Record 123"
end
say time('l')
```
Result:
_134: 08:11:13.430630
134: 08:11:13.437690_  makes a huge difference


Even a smaller predefinition of a high value works well:  
```
imax=50000
x.500='max record'
```
Results in a much better way:
134: 08:12:56.157801
134: 08:12:56.164120

**Comment by Peter-Jacob** [comment]
I'm not sure how CREXX handles arrays internally, but based on some recent experiments with "simulated" stems, I have a hypothesis about what might be going on.

In my stem implementation, I use a hash function to distribute entries across a fixed number of buckets. When a collision occurs, I resolve it by attaching the new value to the colliding entry using a linked list. However, traversing the linked list to find a specific entry is relatively expensive in terms of performance.

To mitigate this, I start with a reasonably large number of buckets — currently 1024 — which amounts to approximately 8KB on a 64-bit machine. This seems like a balanced trade-off between memory usage and lookup performance.

To keep track of the stem statistic, I have a stats command, which looks like this:
```
s9=stemCREATE(50)
do i=1 to 500
     if stemPUT(s9,"Key "i,"Record "i)>0 then say 'duplicate 'i
end
do i=1 to 500
     x=stemGET(s9,"Key "i)
end
call stemSTATS(s9)
```
```
134: Test timeout computed to be: 1500
134: Stem Statistics (2256201099920)
134: -------------------------------
134:  Stem Size         3072
134:  Load Factor       16.276 %
134:  Added Entries     500
134:  Updated Entries   0
134:  Direct Inserts    463
134:  Collision Inserts 37
134:  Empty Buckets     2609
134:  Read Requests     500
134:  Direct Reads      463
134:  Chained Reads     38
134:  Max Chain Depth   3
134:  Avg Probe Depth   0.00
134:  Chain Load (%)    7.40%
```

**Comment by Peter-Jacob** [comment]
issue solved

**Comment by adesutherland** [comment]
Sorry - re-opening - this is not really fixed, I have found some additional issues:

- the new "null r0" instruction which clears the register is not always being applied in the right place by the compiler (e.g. in loops!)

- The "null" instruction is somehow and sometimes is causing long delays - I suspect a memory leak / explosion or something like that

Anyway - investigations continue :-)

**Comment by Peter-Jacob** [comment]
A global array defined in the main rexx is modified several levels deep inside a subprocedure. While a SAY statement within the subprocedure confirms the array has been set, the array is empty when control returns to the calling procedure.

Occurs within the RXPP Precompiler. Minimal reproducible example not yet available.

**Comment by adesutherland** [comment]
> A global array defined in the main rexx is modified several levels deep inside a subprocedure. While a SAY statement within the subprocedure confirms the array has been set, the array is empty when control returns to the calling procedure.
> 
> Occurs within the RXPP Precompiler. Minimal reproducible example not yet available.

Yeah - I know what the problem - essentially the compiler is re-initializing arrays in loops, I'm on it!

**Comment by Peter-Jacob** [comment]
Take your time. I implemented a work around,  RXPP is running . Will commit a version later.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Adrian Sutherland ***@***.***> Datum: 08.08.25  12:35  (GMT+01:00) An: adesutherland/CREXX ***@***.***> Cc: Peter-Jacob ***@***.***>, State change ***@***.***> Betreff: Re: [adesutherland/CREXX] Stem count is not cleared between subprocedure calls (Issue #471) adesutherland left a comment (adesutherland/CREXX#471)

A global array defined in the main rexx is modified several levels deep inside a subprocedure. While a SAY statement within the subprocedure confirms the array has been set, the array is empty when control returns to the calling procedure.
Occurs within the RXPP Precompiler. Minimal reproducible example not yet available.

Yeah - I know what the problem - essentially the compiler is re-initializing arrays in loops, I'm on it!

**Comment by adesutherland** [comment]
@Peter-Jacob I have pushed a fix for the compiler, however it has somehow broken your precompiler. Do you mind investigating?  Have I added a bug to rxc - or is the issue somehow in your workarounds? 

Thanks!

**Comment by adesutherland** [comment]
> [@Peter-Jacob](https://github.com/Peter-Jacob) I have pushed a fix for the compiler, however it has somehow broken your precompiler. Do you mind investigating? Have I added a bug to rxc - or is the issue somehow in your workarounds?
> 
> Thanks!

PS - The error (which is stopping the build) is in creating the tree example

**Comment by Peter-Jacob** [comment]
After applying your fix, there is a general issue with RXPP parameter handling.
RXPP processes incoming parameters using the following loop:

```
do i = 1 to command.0
    j = i + 1
    command.i = upper(command.i)
    if      command.i = '-I'   then infile  = command.j
    else if command.i = '-IN'  then infile  = command.j
    else if command.i = '-O'   then outfile = command.j
    else if command.i = '-OUT' then outfile = command.j
    else if command.i = '-M'   then maclib  = command.j
end
```
The problem is that command.0 is not being initialised correctly.
As a result, incoming parameters are not detected and processed, preventing the RXPP file from being pre-compiled.
This behaviour affects all RXPP files used by the pre-compiler, not just treemap.rxpp.

I have removed the previous fix, and the pre-compile is now running again.

**Comment by adesutherland** [comment]
Ok thanks for the analysis! I will fix

**Comment by adesutherland** [comment]
Pushed a fix

**Comment by Peter-Jacob** [comment]
The first tests went well. I’ll keep testing over the next few days.

**Comment by Peter-Jacob** [comment]
I couldn’t identify any further problems. Feel free to close the issue if you agree.
